# baseURL: "https://techcareconnect.netlify.app/"
title: "Beauty By Mariah"
summaryLength: 20
theme: "hugo-up-business"
languageCode: "en-us"

build:
  buildStats:
    enable: true

  cachebusters:
    - source: "assets/notwatching/hugo_stats\\.json"
      target: "css"

    - source: "(postcss|tailwind)\\.config\\.js"
      target: 'css'

taxonomies:
  series: "series"
  tags: "tags"

params:
  colors:
    bg: "#F4F5EF"
    primary: "#161618"
    secondary: "#A8AF89"
    tertiary: "#998AA6"