site_url: https://mariahest.netlify.app # MAke sure to change this for production
display_url: https://mariahest.netlify.app
logo:
  src: https://mariahest.netlify.app/logo.svg
  show_in_header: true
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'
media_folder: static/images/
public_folder: /img
collections:
  - name: "home"
    label: "Home Page"
    create: false
    editor:
      preview: false
    files:
      - file: "data/home/hero.yaml"
        label: "Hero Section"
        name: "hero_section"
        fields:
          - { label: "Enabled", name: "enable", widget: "boolean" }
          - { label: "Header Text", name: "title", widget: "markdown" }
          - { label: "Smaller Text", name: "text", widget: "markdown" }
          - label: "Buttons"
            name: "buttons"
            widget: "list"
            fields:
              - { label: "Button Text", name: "label", widget: "string" }
              - { label: "Button Link", name: "link", widget: "string" }
      - file: "data/home/cta.yaml"
        label: "Call to Action"
        name: "call_to_action"
        fields:
          - { label: "Enabled", name: "enable", widget: "boolean" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Featured Image", name: "image", widget: "image", required: false }
          - { label: "Action Text", name: "text", widget: "markdown", required: true }
          - label: "Button"
            name: "button"
            widget: "object"
            fields:
              - { label: "Button Text", name: "label", widget: "string" }
              - { label: "Button Link", name: "link", widget: "string" }
      - file: "data/home/testimonials.yaml"
        label: "Testimonials"
        name: "testimonials"
        fields: 
          - { label: "Enabled", name: "enable", widget: "boolean" }
          - label: "Featured Testimony"
            name: "featured"
            widget: "object"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Text", name: "text", widget: "string" }
              - { label: "Client", name: "text", widget: "string" }
          - label: "Other Testimonies"
            name: "items"
            widget: "object"
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - { label: "Client", name: "client", widget: "text" }
     
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'about'
    label: 'About'
    folder: 'content/about'
    create: false
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor: 
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Image', name: 'image', widget: 'image', required: false }
    media_folder: ''
    public_folder: ''